### ISSUE TITLE
Width-x doesn't work for 16 columns

### ISSUE THREAD

**Issue by estevancarlos** [Jellyvision/spread#3]
I'm looking at this part of the calculator:

@if $columns > 8 {
        // Wides
        @for $columns from 1 through $columns / 2 {
          .wide-#{$columns * 4 - 3},
          .wide-#{$columns * 4 - 2},
          .wide-#{$columns * 4 - 1},
          .wide-#{$columns * 4} {
            width: $column-width * $columns * 4;
            max-width: 100%;
          }
}

Shouldn't that address creating widths for 8 columns and more? No class seems to be created as a result of this.

**Comment by estevancarlos** [comment]
Actually I see now that it is only applied to the max columns / 2. Is there a reason for this?

**Comment by jv-dan** [comment]
The "max columns / 2" is because in smaller screen sizes, it automatically scales down to have fewer columns. Note that this reference is inside part of a @media query; is there a particular screen size that isn't behaving as you expect, or a particular class that you expect to exist that doesn't? I noticed the title is referencing "width-x" vs "wide-x", is it possibly just a typo?

**Comment by estevancarlos** [comment]
Well, shucks. Typo. Thanks. I take back my question.
